# Generated by Django 4.2.5 on 2023-09-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='compressed_file',
            field=models.FileField(upload_to='compressed_files'),
        ),
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ImageField(upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_images',
            field=models.ImageField(upload_to='project_images'),
        ),
    ]
