# Generated by Django 4.2.5 on 2023-10-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TC', '0002_alter_project_compressed_file_alter_project_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.AddField(
            model_name='project',
            name='github_username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_images'),
        ),
    ]
